#!/usr/bin/env php
<?php

use ByJG\DbMigration\Console\Application;
use ByJG\DbMigration\Console\CreateCommand;
use ByJG\DbMigration\Console\DatabaseVersionCommand;
use ByJG\DbMigration\Console\DownCommand;
use ByJG\DbMigration\Console\InstallCommand;
use ByJG\DbMigration\Console\ResetCommand;
use ByJG\DbMigration\Console\UpCommand;
use ByJG\DbMigration\Console\UpdateCommand;

$autoload = realpath(__DIR__."/../vendor/autoload.php");
if (!file_exists($autoload)) {
    $autoload = realpath(__DIR__."/../../../autoload.php");
    if (!file_exists($autoload)) {
        throw new \Exception('Autoload not found. Did you run `composer dump-autoload`?');
    }
}
require_once($autoload);

$application = new Application('Migrate Script by JG', '4.1.0');
//$application->add(new ResetCommand());
//$application->add(new UpCommand());
//$application->add(new DownCommand());
//$application->add(new CreateCommand());
$application->add(new DatabaseVersionCommand());
//$application->add(new InstallCommand());
//$application->add(new UpdateCommand());
$application->run();
